package me.cocoblue.passkeysample.domain.common;

public enum AuditLogActionType {
  CREATE_SITE,
  UPDATE_SITE,
  DELETE_SITE,
  UPDATE_ASSIGNED_AGENT,
  DELETE_ASSIGNED_AGENT,
  ADD_SITE_ALIAS,
  REMOVE_SITE_ALIAS,
  CREATE_SITE_GROUP,
  UPDATE_SITE_GROUP,
  DELETE_SITE_GROUP,
  // Agent audit log
  CREATE_AGENT,
  UPDATE_AGENT,
  DELETE_AGENT,
  REGENERATE_AGENT_TOKEN,
  // Notification audit log
  CREATE_NOTIFICATION,
  UPDATE_NOTIFICATION,
  DELETE_NOTIFICATION,
}
